export const ZERO = 0;
export const ONE = 1;
export const TWO = 2;
export const THREE = 3;
export const FOUR = 4;
export const FIVE = 5;
export const SIX = 6;
export const SEVEN = 7;
export const EIGHT = 8;
export const NINE = 9;
export const TEN = 10;
export const TWENTY = 20;
export const THIRTY= 30;
export const FOUR_HUNDRED_SIXTY_FOUR = 464;
export const THOUSAND = 1000;
export const THREE_THOUSAND = 3000
export const THREE_THOUSAND_TWENTY_FOUR = 1024;
